name: Pylint

on:
  workflow_call:
    inputs:
      os:
        type: string
        description: "The operating system to run the workflow on."
        default: ubuntu-latest
      branch:
        type: string
        description: "The branch to run the workflow on."
        default: ${{ github.ref }}

jobs:
  build:
    name: "Stable"
    runs-on: ${{ inputs.os }}
    permissions:
      contents: read
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_stable.txt
          pip install pylint
      - name: Pylint analysis
        run: |
          pylint --enable-all-extensions --extension-pkg-allow-list=orjson,ujson --disable=R,C,W $(git ls-files '*.py')
